project:
  type: website
  post-render: scripts/post-render.py

format:
  html:
    theme: flatly
    css:
      - great-theme.css
    toc: true
    grid:
      sidebar-width: 270px
      body-width: 950px
      margin-width: 225px
      gutter-width: 1rem

website:
  title: "My Python Package"
  description: "Documentation for my awesome Python package"
  navbar:
    logo: assets/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: reference/
        text: Reference
    right:
      - icon: github
        href: https://github.com/yourname/yourpackage